version: "3.9"

services:
  database:
    image: postgres:16.3
    container_name: book-management-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: book-management
    volumes:
      - ./dockerconfig/init-db-script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "5432:5432"
    networks:
      - book-management-network

  restaurant-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    container_name: book-management-api
    depends_on:
      - database
    networks:
      - book-management-network

networks:
  book-management-network: