server:
  port: 8090

spring:
  application:
    name: book-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/book-management
    username: root
    password: secret
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      pool-name: book-management-connection-pool
      connection-test-query: select 1

  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        format_sql: true
        show_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: NONE

  threads:
    virtual:
      enabled: true

